# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I7v5lZXAY9iBpukW_UgEw_ON-CXvMRF6
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("golammostofas/the-verdict")

print("Path to dataset files:", path)

with open("the-verdict.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

print("The total number of characters are: ", len(raw_text))
print(raw_text[:99])

"""# Step 1: Tokenize the entire short story"""

import re
result=re.split(r'([,.]|\s)', raw_text)
print(result)

"""Removing the white spaces"""

result= [item for item in result if item.strip()]
print(result)

Including the other special chracters also

result=re.split(r'[,.:;?_!"()\']|--|\s', raw_text)
result=[item.strip() for item in result if item.strip()]
print(result)

print(len(result))

"""# Step 1: Tokenize the entire short story"""
